version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:8080"
    depends_on:
      - backend
